/**
 * Resolve the knomit web UI source set by walking its import graph.
 *
 * The set is REF-DEPENDENT: at master it is 24 files importing only react,
 * react-dom and react-markdown; at dev, FactBody additionally pulls ./markdown
 * (markdown.tsx + markdown.css + remark-gfm). A hardcoded manifest would break
 * silently whenever KNOMIT_REF moves, so we discover it instead.
 */

/** Seed components: the four /explore surfaces plus the shell's time-travel hook. */
export const SEEDS = [
  'LeftPanel.tsx', 'RightPanel.tsx', 'EdgesRail.tsx', 'FilterBar.tsx',
  'TrailBreadcrumb.tsx', 'ErrorBoundary.tsx', 'useTimeTravel.ts',
  'useNavigationManager.ts',
];

const CANDIDATE_SUFFIXES = ['', '.tsx', '.ts', '.css'];
// The first alternative's middle excludes ";" deliberately: a real
// `import/export ... from '...'` is always a single ES statement with no
// semicolon before its own `from` clause. Without that bound, the original
// `[\s\S]*?` scan runs past an `export const x = {...}` and can match an
// unrelated later `from` — e.g. upstream's `api.ts` has
// `export const api = { ...; if (from) p.set('from', from); ... }`, where the
// literal `'from'` (a query param name) sits right after the word "from" and
// gets misread as a module specifier's opening quote.
const IMPORT_RE = /(?:^|\n)\s*(?:import|export)[^;]*?from\s*['"]([^'"]+)['"]|(?:^|\n)\s*import\s*['"]([^'"]+)['"]/g;

/**
 * @param read  (path) => Promise<string|null> — null means "not found".
 * @param seeds entry filenames, relative to the UI source root.
 * @returns {Promise<{files: string[], bareDeps: string[]}>}
 */
export async function resolveImportGraph(read, seeds = SEEDS) {
  const sources = new Map();   // path -> source text
  const bare = new Set();
  const queue = [...seeds];

  while (queue.length) {
    const file = queue.pop();
    if (sources.has(file)) continue;

    const src = await read(file);
    if (src === null) throw new Error(`vendor-ui: could not read seed or import "${file}"`);
    sources.set(file, src);

    if (file.endsWith('.css')) continue;    // CSS has no JS imports we follow

    for (const spec of specifiers(src)) {
      if (!spec.startsWith('.')) {
        // Strip subpath (e.g. "react-dom/client" -> "react-dom") for the dep list.
        bare.add(spec.startsWith('@') ? spec.split('/').slice(0, 2).join('/') : spec.split('/')[0]);
        continue;
      }
      const base = spec.replace(/^\.\//, '');
      let resolved = null;
      for (const suffix of CANDIDATE_SUFFIXES) {
        const candidate = base + suffix;
        if (sources.has(candidate)) { resolved = candidate; break; }
        if (await read(candidate) !== null) { resolved = candidate; break; }
      }
      if (!resolved) throw new Error(`vendor-ui: ${file} imports "${spec}" which could not be resolved`);
      queue.push(resolved);
    }
  }

  return { files: [...sources.keys()], bareDeps: [...bare] };
}

function specifiers(src) {
  const out = [];
  IMPORT_RE.lastIndex = 0;
  let m;
  while ((m = IMPORT_RE.exec(src)) !== null) out.push(m[1] ?? m[2]);
  return out.filter(Boolean);
}

/**
 * The generated api.ts barrel. ESM gives an explicit named export precedence
 * over `export *`, so `api` resolves to our bundle-backed implementation while
 * every type and pure helper falls through to upstream.
 */
export function renderApiBarrel() {
  return [
    `// GENERATED by scripts/sync.mjs — do not edit.`,
    `// Upstream's api.ts is vendored beside this file as upstreamApi.ts. We`,
    `// re-export its ~40 types and pure helpers, then shadow the one thing that`,
    `// talks HTTP: the \`api\` object. An explicit named export wins over the`,
    `// star re-export, so no vendored component needs changing.`,
    `export * from './upstreamApi';`,
    `export { api } from '../../lib/bundleApi';`,
    ``,
  ].join('\n');
}
